// PHASE_02 FROZEN - do not modify the union type
export type ReasonCode =
  | "REGIME_LOW_CONFIDENCE"
  | "REGIME_AMBIGUOUS"
  | "REGIME_EVENT_DRIVEN"
  | "REGIME_HIGH_VOLATILITY"
  | "REGIME_TREND_EXHAUSTED"
  | "DELEVERAGING_VACUUM"
  | "PARTICIPANT_LONG_CROWDED"
  | "PARTICIPANT_SHORT_CROWDED"
  | "PARTICIPANT_CONFIDENCE_TOO_LOW"
  | "PARTICIPANT_BASIS_DIVERGENCE"
  | "LIQUIDITY_SWEEP_CONFIRMED"
  | "LIQUIDITY_SWEEP_REJECTED"
  | "STRUCTURE_SCORE_TOO_LOW"
  | "STRUCTURE_CONFLUENCE_BOOST"
  | "STRUCTURE_CONFIRMATION_PENDING"
  | "STRUCTURE_CONFIRMATION_INVALIDATED"
  | "RISK_REWARD_TOO_LOW"
  | "CORRELATED_EXPOSURE_LIMIT"
  | "STOP_DISTANCE_TOO_WIDE"
  | "SESSION_LOW_LIQUIDITY_DISCOUNT"
  | "EVENT_WINDOW_WATCH_ONLY"
  | "MACRO_DOWNGRADED"
  | "MACRO_BLOCKED"
  | "DAILY_TREND_COUNTER"   // 信号方向与日线趋势相反（已降级）
  | "DAILY_TREND_ALIGNED"   // 信号方向与日线趋势一致（已标记，无额外加成）
  | "ORDER_FLOW_COUNTER"    // 信号方向与CVD订单流相反（已降级）—— PHASE_18
  | "ORDER_FLOW_ALIGNED"    // 信号方向与CVD订单流一致（已标记，无额外加成）—— PHASE_18
  | "EQUAL_LEVEL_LIQUIDITY"; // Setup 入场区与等高等低区域重叠（评分加成）—— PHASE_19
